<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

$button_name = $this->getBackButtonName();

?>

<?php if ($this->isButtonEnabled()==false) return; ?>

<ul id="payment_form_<?php echo $this->getMethodCode(); ?>" class="form-list">

    <li class="klarna_kcomethod">

    <?php if ($this->isButtonNameUrl($button_name)): ?>
	    <a href="#" onclick="klarnaCheckoutGo('<?php echo $this->getUrl('checkout/klarna/kcomethod') ?>')"><span><span><img src="<?php echo $button_name?>"/></span></span></a>
    <?php else: ?>
	    <a href="#" class="button" onclick="klarnaCheckoutGo('<?php echo $this->getUrl('checkout/klarna/kcomethod') ?>')"><span><span><?php echo $button_name?></span></span></a>
    <?php endif; ?>

    </li>

</ul>

