<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Coming_Soon
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */


$languages = array();
foreach ($this->getStores() as $_lang) {
	if($_lang->getId() == $this->getCurrentStoreId()) {
		$_lang->setIsCurrent(true);
	}
	$code = explode('_', $_lang->getLocaleCode());
	if(isset($languages[$code[0]]) && $languages[$code[0]]->getIsCurrent()) {
		continue;
	}
	$languages[$code[0]] = $_lang;
}
?>
<?php if(count($languages)>1): ?>
<div class="form-language">
    <label for="select-language"><?php echo $this->__('Your Language:') ?></label>
    <ul>
    <?php foreach ($languages as $code => $_lang): ?>
        <li><a href="<?php echo $_lang->getCurrentUrl(); ?>" class="flag-<?php echo $code; ?> <?php echo $_lang->getIsCurrent()? 'plcs-active' : ''; ?>"><?php echo $this->escapeHtml($_lang->getName()); ?></a></li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>