<?php if(count($this->getStores())>1): ?>
    <div class="form-language">
        <div class="langs-wrapper">
            <?php foreach ($this->getStores() as $_lang): ?>
                <a class="lang-flag" href="<?php echo $this->getCurrentUrl() . '?___store=' . $_lang->getCode();?>"><img src="<?php echo $this->getSkinUrl('images/flags/' . $_lang->getCode() . '.png');?>" alt=""></a>
            <?php endforeach;?>
        </div>
    </div>
<?php endif;?>