<?php
$_helper = Mage::helper('catalog/output');
$_product = $this->getProduct();
$addition_cls = $this->getData('addition_cls');
$title = $this->getData('title');

/** THUMBNAIL **/
$imagesize = $this->getData('image_size');

$array_size = explode("x", $imagesize);
$image_width = isset($array_size[0])?(int)$array_size[0]:0;
$list_image_width = $image_width?$image_width: 300;
$image_height = isset($array_size[1])?(int)$array_size[1]:0;
$list_image_height = $image_height?$image_height: 300;


$enable_wrapper = $this->getData('enable_wrapper');
$swap_image = $this->getData('show_swap');
$swap_image_number = $this->getData('swap_index');
$swap_image_number = $swap_image_number?$swap_image_number:0;

$popupsize = $this->getData('popup_size');

$array_pop_size = explode("x", $popupsize);
$popup_image_width = isset($array_pop_size[0])?(int)$array_pop_size[0]:0;
$popup_image_width = $popup_image_width?$popup_image_width: 600;
$popup_image_height = isset($array_pop_size[1])?(int)$array_pop_size[1]:0;
$popup_image_height = $popup_image_height?$popup_image_height: 800;

//If exists ves tempcp
$is_ves_tempcp = $this->checkModuleInstalled("Ves_Tempcp");
if($is_ves_tempcp) {
    $helper = Mage::helper("ves_tempcp/framework")->getFramework( );
    $themeConfig = $helper->getConfig();
}

$id = rand().time();
?>
<?php if($enable_wrapper):  //If enable wrapper for block ?>
<div class="widget-singleproduct block <?php echo $addition_cls; ?>">
	<?php if( $title != '' ){ ?>
	<div class="block-title">
		<?php echo $title; ?>
	</div>
	<?php } ?>
	<div class="widget-inner block-content product-block">
<?php else: ?>
    <div class="product-block <?php echo $addition_cls; ?>">
<?php endif; ?>
		<?php
            $swap_class = "";
            $productId = $_product->getId();
            if($swap_image && $hover_image = $this->getProductImage($_product, $swap_image_number, $list_image_width, $list_image_height)) {
                    $swap_class = "swap";
            }
        ?>
        <div class="image <?php echo $swap_class; ?>">
                <?php //================ Show sale label ============ ?>
                <?php 
                if($this->getData('show_sale_label')) {
                    // Get the Special Price

                    $specialprice = $_product->getSpecialPrice(); 
                    // Get the Special Price FROM date
                    $specialPriceFromDate = $_product->getSpecialFromDate();
                    // Get the Special Price TO date
                    $specialPriceToDate = $_product->getSpecialToDate();
                    // Get Current date
                    $today =  time();
                 
                    if ($specialprice) {
                        if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
                ?>
                        <span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
                <?php  
                        }
                    }
                }
                ?>
                <?php //================ End Show sale label ============ ?>

                <?php //================ Show new label ============ ?>
                 <?php
                    if($this->getData('show_new_label')) {
                        $is_new = $this->checkProductIsNew( $_product );
                        
                        if($is_new) { ?>
                        <span class="new-icon"><span><?php echo $this->__("New");?></span></span>
                        <?php

                        }
                    }
                ?>
                <?php //================ End Show new label ============ ?>

               <?php //Product Image ?>
               <div class="product-img img">
                    <?php if( $this->getData('show_image') ): //Show product image or not ?>
                    <?php //================ Show product image ============ ?>
                   
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image img">

                     <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                    </a>
                    
                    <?php //================ End Show product image ============ ?>

                    <?php //================ Show swap image ============ ?>
                    <?php if($swap_image && $swap_class) { ?>
                            <span class="hover-image">
                                <a class="img" href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">

                                    <img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                </a>
                            </span>
                    <?php } ?>
                    <?php //================ End Show swap image ============ ?>
                    <?php endif; ?>

                    <?php //================ Show quickview ============ ?>
                    <?php if ($this->getData('show_quickview') && $is_ves_tempcp) { ?>
                        <a class="a-quickview ves-colorbox" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getId() ); ?>"><span><?php echo $this->__('Quick View'); ?> </span></a>
                    <?php } ?>
                    <?php //================ End Show quickview ============ ?>

                    <?php //================ Show image popup ============ ?>
                    <?php if( $this->getData('show_image_popup') ): ?>

                        <a href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"> <span><?php echo $this->__('Zoom image'); ?></span> </a>
                    <?php endif; ?>
                    <?php //================ End Show image popup ============ ?>
            </div>
        </div> <!-- End product image -->
        <?php // Product meta ?>
        <div class="product-meta product-shop">
            <div class="left">
                <?php //================ Show product price ============ ?>
                <?php if($this->getData('show_price')): ?>
                    <div class="price" >
                        <?php echo $this->getPriceHtml($_product, true, '-widget-singleproduct'.$id) ?>
                    </div>
                <?php endif; ?>
                <?php //================ End Show product price ============ ?>

                <?php //================ Show product title ============ ?>
                <?php if( $this->getData('show_title') ): ?>
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h3 class="product-name name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h3>
                <?php endif; ?>
                <?php //================ End Show product title ============ ?>

                <?php //================ Show product review ============ ?>
                <?php if($this->getData('show_review')) { ?>
                <?php echo $this->getReviewsSummaryHtml($_product, true, true)?>
                <?php } ?>
                <?php //================ End Show product review ============ ?>

                <?php //================ Show product short description ============ ?>
                <?php if($this->getData('show_short_description') && $_product->getShortDescription()): ?>
                    <div class="desc std">
                        <?php
                            $desc_maxchar = $this->getData('desc_maxchar');
                            $desc_maxchar = $desc_maxchar?(int)$desc_maxchar:100;
                            $product_short_desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
                            echo $this->subString($product_short_desc, $desc_maxchar, "");
                        ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true); ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                <?php endif; ?>
                <?php //================ End Show product short description ============ ?>
            </div> <!-- End left -->

            <div class="right">
                <?php //================ Show add to cart button ============ ?>
                <?php if($this->getData('show_addtocart')): ?>
                <div class="action">
                    
                    <div class="cart">
                        <?php if($_product->isSaleable()): ?>
                                <?php if($is_ves_tempcp): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-shopping-cart" onclick="<?php if($themeConfig->get("enable_ajaxcart", 0)) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><?php echo $this->__('Add to cart') ?></span> </button>   
                                <?php else: ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-shopping-cart btn-outline" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span> </button>
                                <?php endif; ?>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?> 
                    </div>
                   
                </div>
                <?php endif; ?>
                <?php //================ End Show add to cart button ============ ?>   

                <?php //================ Show wishlist and compare links ============ ?>
                <?php if($this->hasData('show_wishlist') || $this->hasData('show_compare')): ?>
                    <ul class="add-to-links">
                        <li class="link-wishlist">
                            <?php if ($this->hasData('show_wishlist') && $this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" ><?php echo $this->__('Wishlist') ?></a>
                            <?php endif; ?>
                        </li>

                        <li class="link-compare">
                            <?php if($this->hasData('show_compare') && $_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Compare') ?></a>
                            <?php endif; ?>
                        </li>
                    </ul>
                <?php endif; ?>
                <?php //================ End Show wishlist and compare links ============ ?>

                <?php //================ Show countdown timer ============ ?>
                <?php
                if($_product->getSpecialToDate() != '' && $this->getData('show_timer_countdown')){
                    $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
                    if ($date1 == "0:00:00") {
                        $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
                    }else{
                        $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
                    }
                    ?>
                    <div class="productdeals">
                        <div class="item-detail">
                            <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>
                        </div>
                        <div id="item<?php echo $id; ?>countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
                        <script type="text/javascript">
                            jQuery(document).ready(function($){
                                $("#item<?php echo $id; ?>countdown_<?php echo $_product->getId(); ?>").lofCountDown({
                                    formatStyle:2,
                                    TargetDate:"<?php echo $targetDate; ?>",
                                    DisplayFormat:"<ul><li>%%D%% <div><?php echo $this->__('Day');?></div></li><li> %%H%% <div><?php echo $this->__('Hours');?></div></li><li> %%M%% <div><?php echo $this->__('Mins');?></div></li><li> %%S%% <div><?php echo $this->__('Secs');?></div></li></ul>",
                                    FinishMessage:"<?php echo $this->__('Expired');?>"
                                });
                            });
                        </script>
                    </div>
                <?php } ?>
                <?php //================ End Show countdown timer ============ ?>

                </div><!-- End right -->
            </div> <!-- End product-meta product-shop -->
                
        </div> <!-- End product-block -->

<?php if($enable_wrapper): //If enable wrapper for block?>
</div> <!-- End widget-singleproduct block -->
<?php endif; ?>