<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

?>
        <?php if ($this->addressesAreTheSame()): ?>
            <?php $extraClassStr = ''; ?>
        <?php else: ?>
            <?php $extraClassStr = ' error'; ?>
        <?php endif; ?>

        <?php if ($this->needDateOfBirth()==false): ?>
            <?php if ($this->needAddressSearch()): ?>

                <li>
                    <span class="update-address-indicator" style="display:none;" id="<?php echo $this->getMethodCode(); ?>_update_address_span"><img alt="Search" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"/></span>
                    <span id="<?php echo $this->getMethodCode(); ?>_update_address_message" class="klarna_msg_txt"></span>
                </li>

                <?php if ($this->shippingSameAsBilling()): ?>
                    <li class="klarna_notification<?php echo $extraClassStr; ?>"><?php echo Mage::helper('klarna')->__('Please note that your official address will be used for shipping and billing address when you place your order'); ?></li>
                <?php else: ?>
                    <li class="klarna_notification<?php echo $extraClassStr; ?>"><?php echo Mage::helper('klarna')->__('Please note that your official address will be used for shipping address when you place your order'); ?></li>
                <?php endif; ?>

            <?php else: ?>

                <?php if (!$this->validShippingAndBillingAddress()): ?>
                    <li class="klarna_notification error"><?php echo Mage::helper('klarna')->__('Name and country must be the same for shipping and billing address!'); ?></li>
                <?php else: ?>
                    <?php if ($this->shippingSameAsBilling()): ?>
                        <li class="klarna_notification<?php echo $extraClassStr; ?>"><?php echo Mage::helper('klarna')->__('Please note that the shipping address will be used for both shipping and billing address when you place your order'); ?></li>
                    <?php endif; ?>
                <?php endif; ?>

            <?php endif; ?>

        <?php else: ?>

            <?php if (!$this->validShippingAndBillingAddress()): ?>
                <li class="klarna_notification error"><?php echo Mage::helper('klarna')->__('Name and country must be the same for shipping and billing address!'); ?></li>
            <?php else: ?>
                <?php if ($this->shippingSameAsBilling()): ?>
                    <li class="klarna_notification<?php echo $extraClassStr; ?>"><?php echo Mage::helper('klarna')->__('Please note that the shipping address will be used for both shipping and billing address when you place your order'); ?></li>
                <?php endif; ?>
            <?php endif; ?>

        <?php endif; ?>
