<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

$klarnaSetup = $this->getKlarnaSetup();
$_fieldName = $this->getMethodCode() .'_consent_span';
$_spanText = '<span id="' . $_fieldName .'"></span>';
$_termsLink = $this->getTermsUrlLink();
?>

<?php if ($this->needConsent()): ?>

            <li>

                <div class='input_combo'>
                    <input type="checkbox" name="payment[<?php echo $this->getMethodCode(); ?>_consent]" id="<?php echo $this->getMethodCode(); ?>_consent" style="float: left; margin-right: 3px"  class="validate-checkbox" value="consent" />
                    <label for="<?php echo $this->getMethodCode(); ?>_consent"><?php echo Mage::helper('klarna')->__('By submitting my data I consent to the processing of my data by Klarna for the purposes of identity- and credit assessment and the settlement of the purchase. I may revoke my %s for the processing of data and for the purposes for which this is possible according to law. The general %s apply.', $_spanText, $_termsLink); ?></label>
                </div>

            </li>

<?php endif; ?>
