<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

$currentDobYear = $this->getCurrentDobYear();
$currentDobMonth = $this->getCurrentDobMonth();
$currentDobDay = $this->getCurrentDobDay();

?>

        <?php if ($this->needDateOfBirth()): ?>

            <li class="klarna_dob">

                <label for="<?php echo $this->getMethodCode(); ?>_dob_year">
                    <?php echo Mage::helper('klarna')->__('Date of birth') ?>
                </label>
                <br/>
                <input id="<?php echo $this->getMethodCode(); ?>_dob_day" type="text" name="payment[<?php echo $this->getMethodCode(); ?>_dob_day]" placeholder="<?php echo Mage::helper('klarna')->__('Day') ?>" value='<?php echo $currentDobDay; ?>' maxlength="2" />
                <input id="<?php echo $this->getMethodCode(); ?>_dob_month" type="text" name="payment[<?php echo $this->getMethodCode(); ?>_dob_month]" placeholder="<?php echo Mage::helper('klarna')->__('Month') ?>" value='<?php echo $currentDobMonth; ?>' maxlength="2" />
                <input id="<?php echo $this->getMethodCode(); ?>_dob_year" type="text" name="payment[<?php echo $this->getMethodCode(); ?>_dob_year]" placeholder="<?php echo Mage::helper('klarna')->__('Year') ?>" value='<?php echo $currentDobYear; ?>' maxlength="4" />

            </li>

        <?php endif; ?>
