<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

$currentGender = $this->getCurrentGender();
$female_selected = '';
$male_selected = '';
$not_selected = '';
if ($currentGender===1 || $currentGender==="1") {
    $male_selected = ' checked="checked" ';
} elseif ($currentGender===0 || $currentGender==="0") {
    $female_selected = ' checked="checked" ';
} else {
    $not_selected = ' checked="checked" ';
}

?>

        <?php if ($this->needGender()): ?>

            <li>
                <label>
                    <?php echo Mage::helper('klarna')->__('Gender') ?>
                </label>
                <br/>

                <div class="gender-input-box">
                    <input type="radio" name="payment[<?php echo $this->getMethodCode(); ?>_gender]" value="1" id="<?php echo $this->getMethodCode(); ?>_gender_male" <?php echo $male_selected; ?> />
                    <label style="float: none;" for="<?php echo $this->getMethodCode(); ?>_gender_male"> <?php echo Mage::helper('klarna')->__('Male'); ?></label>
                    
                    <input type="radio" name="payment[<?php echo $this->getMethodCode(); ?>_gender]" value="0" id="<?php echo $this->getMethodCode(); ?>_gender_female" <?php echo $female_selected; ?> />
                    <label style="float: none;" for="<?php echo $this->getMethodCode(); ?>_gender_female"> <?php echo Mage::helper('klarna')->__('Female'); ?></label>

                    <input type="radio" name="payment[<?php echo $this->getMethodCode(); ?>_gender]" value="-1" id="<?php echo $this->getMethodCode(); ?>_gender_not_selected" <?php echo $not_selected; ?> style="display: none;"/>
                </div>
            </li>

        <?php endif; ?>
