<?php if($this->getItems()->getSize()): ?>

	<section class="latest-offer related-product-carousal">
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<h1 class="section-heading"><?php echo Mage::getStoreConfig('vanimeli/inchoo_group_other/relatedlbl'); ?></h1>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					 <div id="latest_offers" class="products-grid products-grid--max-3-col first last odd">
						<?php foreach($this->getItems() as $_item): ?>
							<li class="item last">
								<div class="prod-main_section">
									<a class="product-image" href="<?php echo $_item->getProductUrl() ?>"><img class="img-responsive " alt="" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(400) ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
								
								<?php if($_item->getSpecialPrice()){
									?>
									<p class="sale"><?php echo $this->__('Sale')?></p>
									<?php
								}else{
									?>
									<?php 
								}
								?>
								<div class="product-info grid-proInfo" style="min-height: 100px;">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $_item->getName() ?></a></h2>
									<p class="short_desc"><?php echo $_item->getShortDescription();?></p>
									<?php if($_item->getSpecialPrice()){
										?>
										<div class="price-box"><span class="past-price">was <?php echo Mage::helper('core')->currency($_item->getPrice(), true, false);?></span>&nbsp;&nbsp;&nbsp;<span class="present-price">now <?php echo Mage::helper('core')->currency($_item->getSpecialPrice(), true, false);?></span></div>
										<?php
									}else{
										?>
										<div class="price-box"><?php echo Mage::helper('core')->currency($_item->getPrice(), true, false);?></div>
										<?php 
									}
									?>
								</div>
							</div>
								<div class="related-pro-buy"><!-- <a class="" href="<?php //echo $_item->getProductUrl() ?>">View &amp; Buy</a>--></div>
							</li>
						<?php endforeach ?>
					</div>
				</div>


			</div>
		</div>
	</section><?php endif ?>
