<?php 
/*Owl Carousel Setting*/
	$auto_play_mode = $this->getCarouselConfig("auto_play");
	$interval = (int)$this->getCarouselConfig("interval");
	$lazy_load_image = $this->getCarouselConfig("lazy_load_image", 0);
	$loop = (int)$this->getCarouselConfig("loop", 1);
	$slide_by = (int)$this->getCarouselConfig("slide_by", 1);
	$margin_item = $this->getCarouselConfig("margin_item", 0);
	$show_nav = (int)$this->getCarouselConfig("show_navigator", 1);
	$rtl = (int)$this->getCarouselConfig("rtl", 0);
	$mouse_drag = (int)$this->getCarouselConfig("mouse_drag", 1);
	$touch_drag = (int)$this->getCarouselConfig("touch_drag", 1);
	$mobile_items = (int)$this->getCarouselConfig("mobile_items", 1);
	$tablet_items = (int)$this->getCarouselConfig("tablet_items", 2);
	$tablet_small_items = (int)$this->getCarouselConfig("tablet_small_items", 2);
	$portrait_items = (int)$this->getCarouselConfig("portrait_items", 3);
	$large_items = (int)$this->getCarouselConfig("large_items", 5);
	$custom_items = $this->getCarouselConfig("custom_items", "");

	$carousel_responsive = (int)$this->getCarouselConfig("carousel_responsive", 1);
	$cols = (int)$this->getCarouselConfig("default_items", 4);
	$cols = !empty($cols)?(int)$cols:4;
	$itemsperpage = (int)$this->getConfig("max_items", 1);
	$auto_play = $auto_play_mode?"true":"false";
	
	$default_items = $cols;

	$moduleId = "vesgallery".rand().time();

	$show_title = (int)$this->getConfig("show_title", 1);
	$show_link = (int)$this->getConfig("show_link", 1);
	$show_description = (int)$this->getConfig("show_description", 1);
	$show_description = (int)$this->getConfig("show_description", 1);
	$enable_popup = (int)$this->getConfig("enable_popup", 1);
?>
<?php 
	$style = "";
	if( $this->getConfig("moduleHeight") !="auto" ){
		$style .=";height:".(int) $this->getConfig("moduleHeight")."px";
	}
	if( $this->getConfig("moduleWidth") !="auto" ){
		$style .=";width:".(int) $this->getConfig("moduleWidth")."px";
	}
?>
<?php if( count($this->getImages()) ) { ?>
<div class="ves-gallery" style="position:relative;<?php echo $style;?>">
	<?php if($this->getConfig('title')){?>
	<div class="block-title">
		<h2><?php echo $this->getConfig('title')?></h2>
	</div>
	<?php }?>
	

		<div class="block-content">
			<div class="box-gallery masonry">
				<ul class="grid row" id="grid<?php echo $moduleId; ?>">
						<?php $number = 1; ?>
						<?php foreach ($this->getImages() as  $k => $image ):  ?>
								<li class="grid-item <?php echo isset($image['classes'])?$image['classes']:'';?>">
									<a class="group-file<?php echo $moduleId?> group-gallery-<?php echo $moduleId?>" rel="group-gallery-<?php echo $moduleId?>" href="<?php echo $image['imageURL'];?>" title="<?php echo $image['title'];?> - <?php echo $image['description']; ?>">
										<img src="<?php echo $image['thumbnailURL'];?>" alt="<?php echo $image['title'];?>"/>
									</a>
									<?php if($show_title || $show_description): ?>
									<div class="desc-gallery">
										<?php if($show_title): ?>
								        <div class="gellary-title">
								        	<?php if($image['links']): ?>
								        		<a href="<?php echo $image['links']; ?>"><?php echo $image['title'];?></a>
								        	<?php else: ?>
								        		<?php echo $image['title'];?>
								        	<?php endif; ?>
								        </div>
								    	<?php endif; ?>
								    	<?php if($show_description): ?>
								        <div class="gellary-description"><?php echo !$crop_desc?$image['description']:$this->subString($image['description'], 100, "");?></div>
							        	<?php endif; ?>
							        </div>
							        <?php endif; ?>  
							        <?php if($image['links'] && $show_link): ?>
											<div class="links"> 
												<a href="<?php echo $image['links']; ?>" ><?php echo $this->__("Link"); ?></a>
											</div>
									<?php endif; ?>
								
								</li>
						<?php endforeach; ?>
					</ul>
		</div>
</div>

</div>

<script type="text/javascript">
jQuery(window).load(function() {
	var elem = document.querySelector('#grid<?php echo $moduleId; ?>');
	var msnry = new Masonry( elem, {
	  // options
	  itemSelector: '#grid<?php echo $moduleId; ?> .grid-item'
	});
});
</script>
<?php if($enable_popup): ?>
<script type="text/javascript">
jQuery(document).ready(function( $ ){
	$(".group-file<?php echo $moduleId?>").colorbox({rel:'group-gallery-<?php echo $moduleId; ?>', overlayClose: true, opacity: 0., scalePhotos: true, maxWidth: '100%', maxHeight: '100%'5});
});
</script>
<?php endif; ?>
<?php } //end if ?>