<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Coming_Soon
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<script type="text/javascript">
	var modLivePath			= '<?php echo $this->jsQuoteEscape(Mage::helper("adminhtml")->getUrl("comingsoon_admin/adminhtml_mode/preview", array("mode" => "live", "website" => Mage::app()->getRequest()->getParam("website"), "store" => Mage::app()->getRequest()->getParam("store")))); ?>';
	var modComingsoonPath	= '<?php echo $this->jsQuoteEscape(Mage::helper("adminhtml")->getUrl("comingsoon_admin/adminhtml_mode/preview", array("mode" => "comingsoon", "website" => Mage::app()->getRequest()->getParam("website"), "store" => Mage::app()->getRequest()->getParam("store")))); ?>';
	var modMaintenancePath	= '<?php echo $this->jsQuoteEscape(Mage::helper("adminhtml")->getUrl("comingsoon_admin/adminhtml_mode/preview", array("mode" => "maintenance", "website" => Mage::app()->getRequest()->getParam("website"), "store" => Mage::app()->getRequest()->getParam("store")))); ?>';
</script>