<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

/*
 * This file is only included in OneStepCheckout. I would have liked to have it in
 * standard checkout as well (instead of in the form files), but it doesn't want to work.
 *
 */

?>

<?php $invoiceFee = $this->getKlarnaInvoiceFeeInfo(); ?>
<?php $klarnaSetupInvoice = $this->getKlarnaSetup(Vaimo_Klarna_Helper_Data::KLARNA_METHOD_INVOICE); ?>
<?php $klarnaSetupAccount = $this->getKlarnaSetup(Vaimo_Klarna_Helper_Data::KLARNA_METHOD_ACCOUNT); ?>
<?php $klarnaSetupSpecial = $this->getKlarnaSetup(Vaimo_Klarna_Helper_Data::KLARNA_METHOD_SPECIAL); ?>

<script type="text/javascript">
    window.addEventListener('DOMContentLoaded', function () {
        insertKlarnaInvoiceElements('<?php echo $klarnaSetupInvoice->getMerchantId(); ?>', '<?php echo $klarnaSetupInvoice->getLocaleCode(); ?>', <?php echo $invoiceFee; ?>);
        insertKlarnaAccountElements('<?php echo $klarnaSetupAccount->getMerchantId(); ?>', '<?php echo $klarnaSetupAccount->getLocaleCode(); ?>');
        insertKlarnaSpecialElements('<?php echo $klarnaSetupSpecial->getMerchantId(); ?>', '<?php echo $klarnaSetupSpecial->getLocaleCode(); ?>');
    });

</script>

