<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */
?>

<?php if ($this->isEnabled()): ?>
<div id="klarna-checkout-newsletter-container" class="klarna-checkout-newsletter-container">
    <h3><?php echo $this->__('Newsletter') ?></h3>
    <input id="klarna-checkout-newsletter-url" type="hidden" value="<?php echo $this->getUrl('checkout/klarna/subscribeToNewsletter') ?>" />
    <input id="klarna-checkout-newsletter-type" type="hidden" value="<?php echo $this->getType() ?>" />
    <?php $checked = $this->isChecked() ? 'checked ' : '' ?>
    <input id="klarna-checkout-newsletter" class="klarna-checkout-newsletter" type="checkbox" name="klarna_checkout_newsletter" <?php echo $checked ?>/>
    <label for="klarna-checkout-newsletter"><?php echo $this->getLabel() ?></label>
</div>
<?php endif; ?>