<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */
?>

<form id="klarna_shipping" class="klarna_block klarna_shipping" action="<?php echo $this->getUrl('checkout/klarna/saveShippingMethod') ?>" method="post">
   	<h3 class="klarna_block-title"><?php echo $this->__('Choose shipping method') ?></h3>
   	<?php echo $this->getChildHtml('available') ?>
    <input type="hidden" name="test" value="testvalue" />
</form>

<script>
    if(document.getElementById('s_method_matrixrate_matrixrate_free') && getCookie('klarnaShippingChanged') != 1) {
    	document.getElementById('s_method_matrixrate_matrixrate_free').checked = true;
        document.cookie = 'klarnaShippingChanged=1; expires=0;';
    }
</script>
