<div id="klarna_sidebar" class="klarna_sidebar col-md-4 col-sm-12">
    <?php echo $this->getChildHtml('other.payment.methods'); ?>

    <?php echo $this->getChildHtml('shipping_method'); ?>

    <?php echo $this->getChildHtml('checkout.cart'); ?>
    <?php echo $this->getChildHtml('klarnacheckout.reward'); ?>
    <?php echo $this->getChildHtml('klarnacheckout.customer_balance'); ?>
    <?php echo $this->getChildHtml('checkout.newsletter'); ?>

    <?php echo $this->getChildHtml('discount'); ?>
</div>