<?php
/**
 * Magestore
 *
 */
?>
<?php
/**
 * Mage_Adminhtml_Block_Sales_Order_Create_Coupons
 *  hainh 23-07-2014
 */
?>
<?php $affiliateCode = Mage::getSingleton('checkout/session')->getData('affiliate_coupon_code'); ?>
<div class="entry-edit box-left">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo Mage::helper('sales')->__('Apply Coupon Code') ?></h4>
    </div>
    <fieldset class="np">
        <div class="content">
            <p><input type="text" class="input-text" id = "coupons:code" value="" name="coupon_code" style="width:200px"  />&nbsp;
                <?php echo $this->getButtonHtml(Mage::helper('sales')->__('Apply'), 'order.applyCoupon($F(\'coupons:code\'))') ?> </p>
                <?php if ($this->getCouponCode()): ?>
                <p><strong><?php echo $this->escapeHtml($this->getCouponCode()) ?></strong> [<a href="#" onclick="order.applyCoupon('');
                        return false;" title="<?php echo Mage::helper('sales')->__('Remove Coupon Code') ?>"><?php echo Mage::helper('sales')->__('Remove') ?></a>]</p>
                <?php endif; ?>
                <?php if (($affiliateCode)&&($affiliateCode!='')): ?>
                <p><strong><?php echo $affiliateCode ?></strong> (Affiliate Coupon Code)  [<a href="#" onclick="order.applyCoupon('removeAffiliateCodeBackend');
                        return false;" title="<?php echo Mage::helper('sales')->__('Remove Affiliate Coupon Code') ?>"><?php echo Mage::helper('sales')->__('Remove') ?></a>]</p>
                <?php endif; ?>
<!--            <button onclick="window.location.href = '<?php echo Mage::helper("adminhtml")->getUrl('affiliatepluscouponadmin/adminhtml_rewrite_create/showinfomation'); ?>'" >show Info</button>
            <?php echo $this->getButtonHtml(Mage::helper('sales')->__('Remove affiliatecode'), 'order.applyCoupon($F(\'removeaffiliatecode\'))') ?> -->

            <?php echo (Mage::getSingleton('customer/session')->getCustomer()->getId()); ?>
            <script type="text/javascript">
                order.overlay('shipping-method-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
                    order.overlay('address-shipping-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
            </script>
        </div> </fieldset>
</div>
</div>
