<?php
/**
 * Request Payment Method Form template
 */
?>
<?php $paymentMethods = $this->getAllPaymentMethod(); ?>
<?php $data = $this->getRequest()->getParams() ?>
<?php
$store_id = Mage::app()->getStore()->getStoreId();
$check_responsvie = Mage::getStoreConfig('affiliateplus/style_config/responsive_enable', $store_id);
 if($check_responsvie)
     $class_name = 'col-lg-9 col-md-9 col-sm-12 col-xs-12';
 else
     $class_name = 'col-lg-9 col-md-9 col-sm-9 col-xs-9';
?>
<div class="aff-main-content <?php echo $class_name; ?>">
<div class="aff-title affiliate-request">
    <h1><?php echo $this->__('Request Withdrawal'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="affiliateplus_payment_request_form" action="<?php echo $this->getFormActionUrl() ?>" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <div class = "lable-title" >
            <h2 class="legend"><?php echo $this->__('Request Information') ?></h2>
        </div>
        <ul>
            <div class="form-group">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <?php if ($this->getTaxRate()): ?>
                        <?php $_amount = $this->getRequest()->getParam('amount_incl_tax') ? $this->getRequest()->getParam('amount_incl_tax') : $this->getAmount() ?>
                        <label for="amount_incl_tax" class="required"><?php echo $this->__('Request Amount') ?><em>*</em></label>
                        
                            <input id="amount_incl_tax" type="text" name="amount_incl_tax" class="input-text required-entry validate-greater-than-zero form-control" onchange="checkAmountBalance(this);" value="<?php echo $_amount ?>" />
                       
                    <?php else: ?>
                        <label for="amount" class="required"><?php echo $this->__('Request Amount') ?><em>*</em></label>
                        
                            <input id="amount" type="text" name="amount" class="input-text required-entry validate-greater-than-zero form-control" onchange="checkAmountBalance(this);" value="<?php echo $this->getAmount() ?>" />
                      
                    <?php endif ?>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <label for="balance"><?php echo $this->__('My Balance') ?></label>
                    
                        <strong id="balance"><?php echo $this->getFormatedBalance() ?></strong>
                    
                </div>
            </div>
            <?php if ($this->getTaxRate()): ?>
                <?php $_taxAmount = $_amount * $this->getTaxRate() / (100 + $this->getTaxRate()) ?>
                <div class="form-group">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="amount" class="required"><?php echo $this->__('Amount (Excl. Tax)') ?><em>*</em></label>
                       
                            <input id="amount" type="text" name="amount" class="input-text required-entry validate-greater-than-zero form-control" onchange="changeRealAmount(this);" value="<?php echo $_amount - round($_taxAmount, 2) ?>" />
                       
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label><?php echo $this->__('Tax (%s)', round($this->getTaxRate(), 2) . '%') ?></label>
                        
                            <strong id="withdrawal_tax"><?php echo Mage::app()->getStore()->formatPrice($_taxAmount) ?></strong>
                        
                    </div>
                </div>
            <?php endif ?>
            <?php if (count($paymentMethods) == 1): ?>
                <?php foreach ($paymentMethods as $code => $method): ?>
                    <div class="form-group">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <input type="hidden" id="payment_method_<?php echo $code ?>" value="<?php echo $code ?>" name="payment_method" />
                        </div>
                    </div>
                    <div class="form-group" id="payment_method_<?php echo $code ?>_form">
                        
                        <?php echo $this->getChildHtml("payment_method_form_$code") ?>
                     
                    </div>
                <?php endforeach ?>
            <?php else: ?>
                <?php if (!isset($data['payment_method']) || !$data['payment_method']): ?>
                    <?php foreach ($paymentMethods as $code => $method): ?>
                        <?php $isFirst = $this->methodSelected($code); ?>
                        <div class="form-group">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <input type="radio" id="payment_method_<?php echo $code ?>" value="<?php echo $code ?>" name="payment_method" title="<?php echo $method->getLabel() ?>" class="radio" onclick="changeMethod();" <?php if ($isFirst): ?>checked<?php endif ?> />
                            <label for="payment_method_<?php echo $code ?>" style="float:center;"><?php echo $method->getLabel() ?></label>
                            </div>
                            </div>
                        <div class="form-group payment_method_form" id="payment_method_<?php echo $code ?>_form" <?php if (!$isFirst) echo 'style="display:none"'; ?>>
                           
                            <?php echo $this->getChildHtml("payment_method_form_$code") ?>
                          
                        </div>
                    <?php endforeach ?>
                <?php else: ?>
                    <?php foreach ($paymentMethods as $code => $method): ?>
                        <div class="form-group">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <input type="radio" id="payment_method_<?php echo $code ?>" value="<?php echo $code ?>" name="payment_method" title="<?php echo $method->getLabel() ?>" class="radio" onchange="changeMethod();" <?php if ($data['payment_method'] == $code): ?>checked<?php endif ?> />
                            <label for="payment_method_<?php echo $code ?>" style="float:center;"><?php echo $method->getLabel() ?></label>
                            </div>
                            </div>
                        <div class="form-group payment_method_form" id="payment_method_<?php echo $code ?>_form" <?php if ($data['payment_method'] != $code) echo 'style="display:none"'; ?>>
                            
                            <?php echo $this->getChildHtml("payment_method_form_$code") ?>
                           
                        </div>
                    <?php endforeach ?>
                <?php endif; ?>
            <?php endif ?>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="buttons-set">
        <p class="required">* <?php echo $this->__('Required Fields'); ?></p>
        <button style="float:right;" title="<?php echo $this->__('Send Request'); ?>" class="button button-config" type="button" onclick="submitPayment(this);">
            <span>
                <span>
                    <?php echo $this->__('Send Request'); ?>
                </span>
            </span>
        </button>
        <button type="button" style="float:left;" onclick="javascript:cancelRequest()" class="button button-config">
            <span><span><?php echo $this->__('Cancel') ?></span></span>
        </button>
    </div>
</form>
</div>

<script type="text/javascript">
    
//<![CDATA[
    var affiliateplusPaymentRequestForm = new VarienForm('affiliateplus_payment_request_form', true);
    function checkVerify() {
        var amount = $('amount').value;
        $$('input[type="radio"][name="payment_method"]').each(function(el) {
            if (el.checked) {
                var payment_method = el.value;
                if (payment_method == 'paypal' || payment_method == 'moneybooker') {
                    var email = $(payment_method + '_email').value;
                    var url = '<?php echo $this->getUrl('affiliateplus/index/checkVerify') ?>?payment_method=' + payment_method + '&email=' + email;
                    var request = new Ajax.Request(url, {
                        'onSuccess': function(response) {
                            var result = response.responseText;
                            if (result) {
                                return true;
                            } else {
                                alert(result);
                                showVerifyForm(payment_method, email, amount,null);
                                return false;
                            }

                        }
                    });
                }
            }
        });
        return false;
    }
    function submitPayment(element) {
        var amount = $('amount').value;
        $$('input[type="radio"][name="payment_method"]').each(function(el) {
            if (el.checked) {
                var payment_method = el.value;
                if (payment_method == 'paypal' || payment_method == 'moneybooker') {
                    if (affiliateplusPaymentRequestForm.validator.validate()) {
                        var email = $(payment_method + '_email').value;
                        var url = '<?php echo $this->getUrl('affiliateplus/index/checkVerify') ?>?payment_method=' + payment_method + '&email=' + email + '&amount=' + amount;
                        var request = new Ajax.Request(url, {
                            'onSuccess': function(response) {
                                var result = response.responseText;
                                if (result) {
<?php if (count($paymentMethods) == 1): ?>
                                        affiliateplusPaymentRequestForm.submit();
<?php else: ?>
                                        if ($$('input:checked[type="radio"][name="payment_method"]').pluck('value')[0])
                                            affiliateplusPaymentRequestForm.submit();
                                        else
                                            alert('<?php echo $this->__('Please specify a payment method') ?>');
<?php endif ?>
                                } else {
                                    showVerifyForm(payment_method, email, amount,element);
                                    return false;
                                }

                            }
                        });
                    }
                } else {
<?php if (count($paymentMethods) == 1): ?>
                        affiliateplusPaymentRequestForm.submit();
<?php else: ?>
                        if ($$('input:checked[type="radio"][name="payment_method"]').pluck('value')[0])
                            affiliateplusPaymentRequestForm.submit();
                        else
                            alert('<?php echo $this->__('Please specify a payment method') ?>');
<?php endif ?>
                }
            }
        });
<?php if (count($paymentMethods) == 1): ?>
    <?php // Change By Adam 23/10/2013 - hainh update 24-04-2014  ?>
    <?php //check when select only bank payment - no need to check paypal anymore  ?>
    <?php foreach ($paymentMethods as $code => $value): ?>
        <?php if ($code == 'paypal' || $code == 'moneybooker'): ?>
                    var email = $('paypal_email').value;
                    if (affiliateplusPaymentRequestForm.validator.validate()) {
                        var url = '<?php echo $this->getUrl('affiliateplus/index/checkVerify') ?>?payment_method=paypal&email=' + email + '&amount=' + amount;
                        var request = new Ajax.Request(url, {
                            'onSuccess': function(response) {
                                var result = response.responseText;
                                if (result) {
            <?php if (count($paymentMethods) == 1): ?>
                                        affiliateplusPaymentRequestForm.submit();
            <?php else: ?>
                                        if ($$('input:checked[type="radio"][name="payment_method"]').pluck('value')[0])
                                            affiliateplusPaymentRequestForm.submit();
                                        else
                                            alert('<?php echo $this->__('Please specify a payment method') ?>');
            <?php endif ?>
                                } else {
                                    showVerifyForm('paypal', email,element);
                                    return false;
                                }

                            }
                        });
                    }
        <?php else: ?>
                    affiliateplusPaymentRequestForm.submit();
        <?php endif; ?>
    <?php endforeach; ?>
<?php else: ?>
<?php endif ?>

    }

    function showVerifyForm(method, email, amount,element) {
        var url = '<?php echo $this->getUrl('affiliateplus/index/verifyPayment'); ?>' + '?method=' + method + '&email=' + email + '&amount=' + amount;
         //$('affiliateplus_credit').disabled = true;
        ajaxPopup(url,null,element);
    }

    function changeMethod() {
        $$('input[type="radio"][name="payment_method"]').each(function(el) {
            if (el.checked) {
                $('payment_method_' + el.value + '_form').show();
            } else {
                $('payment_method_' + el.value + '_form').hide();
            }
        });
    }

    var request_amount_max = <?php echo $this->getBalance() ?>;
    function checkAmountBalance(el) {
        el.value = parseFloat(el.value);
        if (el.value < 0)
            el.value = 0;
        else if (el.value > request_amount_max || el.value == 'NaN')
            el.value = request_amount_max;

<?php if ($this->getTaxRate()): ?>
            var taxRate = <?php echo $this->getTaxRate() ?>;
            var taxAmount = el.value * taxRate / (100 + taxRate);
            taxAmount = Math.round(taxAmount * 100) / 100;
            $('withdrawal_tax').innerHTML = formatCurrency(taxAmount, <?php echo $this->getPriceFormatJs() ?>);
            $('amount').value = el.value - taxAmount;
<?php endif ?>
    }

<?php if ($this->getTaxRate()): ?>
        function changeRealAmount(el) {
            var taxRate = <?php echo $this->getTaxRate() ?>;
            var maxRequestAmount = request_amount_max * 100 / (100 + taxRate);
            maxRequestAmount = Math.round(maxRequestAmount * 100) / 100;

            // Refine real amount
            el.value = parseFloat(el.value);
            if (el.value < 0)
                el.value = 0;
            else if (el.value > maxRequestAmount || el.value == 'NaN')
                el.value = maxRequestAmount;

            // update Tax Amount
            var taxAmount = Math.round(el.value * taxRate) / 100;
            $('withdrawal_tax').innerHTML = formatCurrency(taxAmount, <?php echo $this->getPriceFormatJs() ?>);

            // update Amount
            var totalAmount = parseFloat(el.value) + parseFloat(taxAmount);
            totalAmount = Math.round(totalAmount * 100) / 100;
            $('amount_incl_tax').value = totalAmount;
        }
<?php endif ?>

    function cancelRequest() {
        var url = '<?php echo $this->getUrl('affiliateplus/index/index'); ?>';
        window.location.href = url;
    }

    function submitForm() {
        var verifyForm = new VarienForm('verify-email-form', true);
        if (verifyForm.validator.validate())
            $('verify-email-form').submit()
    }

    function notNow() {
        closeAffPopup();
    }

    function sendMail() {
        var method = $('payment_method').value;
        var email = $('email').value;
        var url = '<?php echo $this->getUrl('affiliateplus/index/sendVerifyEmail') ?>?payment_method=' + method + '&email=' + email;
        var request = new Ajax.Request(url, {
            onSuccess: function(response) {
                if (response.responseText) {
                    alert('An authentication code was sent to your email. Please check it again!');
                } else {
                    alert("Can\'t send email. Please check your email is right.");
                }
            }
        });
    }

//]]>
</script>
