<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

?>
<?php $_source  = $this->getSource() ?>
<?php if ($_source): ?>
    <?php $amount = $this->getKlarnaInvoiceFeeAmount(); ?>
    <?php if ($amount!==NULL): ?>
        <tr>
            <td class="label"><?php echo $this->getKlarnaInvoiceFeeLabel() ?></td>
            <td><input type="text" name="creditmemo[vaimo_klarna_fee_refund]" value="<?php echo $amount; ?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="vaimo_klarna_fee_refund" /></td>
        </tr>
        <tr>
            <td colspan="2"><div id="vaimo_klarna_fee_refund_adv"></div></td>
        </tr>

        <script type="text/javascript">
        //<![CDATA[
        Validation.addAllThese([
            ['not-negative-amount', '<?php echo $this->helper('klarna')->__('Please enter a positive number in this field.') ?>', function(v) {
                if(v.length)
                    return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                else
                    return true;
            }]
        ]);

        if ($('vaimo_klarna_fee_refund')) {
            $('vaimo_klarna_fee_refund').advaiceContainer = $('vaimo_klarna_fee_refund_adv');
            unblockKlarnaSubmit('vaimo_klarna_fee_refund');
        }

        function unblockKlarnaSubmit(id) {
            $(id).observe('focus', function(event) {
                if ($$('button[class="scalable update-button disabled"]').size() > 0) {
                    enableElements('submit-button');
                }
            });
        }
        //]]>
        </script>

    <?php endif; ?>
<?php endif; ?>
