<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist */
?>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="my-wishlist">
        <div class="page-title title-buttons">
            <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
                <a href="<?php echo $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>" class="link-rss"><?php echo $this->__('RSS Feed') ?></a>
            <?php endif; ?>
            <h1><?php echo $this->getTitle(); ?></h1>
        </div>
        <?php echo $this->getMessagesBlock()->toHtml() ?>

        <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" method="post">
            <?php echo $this->getChildHtml('top'); ?>
            
                <?php if ($this->hasWishlistItems()): ?>
                        <?php echo $this->getBlockHtml('formkey');?>
                        <?php $column = 3 ; $count = $this->getWishlistItems()->count(); $i = 0; ?>                        
                        <?php foreach ($this->getWishlistItems() as $item) : ?>                        
                        <?php $product = $item->getProduct(); ?>
                       
                        
                        <?php if($i++%$column == 0) : ?>
                        <ul class="wishlist-list">
                        <?php endif; ?>
                        	<li class="<?php echo $i%$column == 0 ? "item last" : "item"?>"> 	
                        		<?php
										$options = $this->getChild('customer.wishlist.item.options')
									    ->setItem($item)
									    ->getConfiguredOptions() 
								?>
									
                        		<h2 class="product-name">
                        			<a href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a>
                        			
                        			
                        		</h2>
                        				
								<a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
								    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(210); ?>" width="210" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
								</a>
								
								<div class="info">
									<?php foreach($this->getSortedChildren() as $childName):?>
									    <?php echo $this->getChildHtml($childName, false);?>
									<?php endforeach;?> 
									<?php echo $this->getPriceHtml($product, empty($options)); ?>
									<!-- 
									<div>
										<label><?php echo $this->__('Qty:');?></label> <input type="text" class="input-text qty validate-not-negative-number" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />
									</div> -->
								</div>
								
								
								<div class="actions">	
									
									<button type="button" onclick="setLocation('<?php echo $this->getItemRemoveUrl($item); ?>')" href="<?php echo $this->getItemRemoveUrl($item); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"  class="button btn-wishlist-remove"><span><span><?php echo $this->__('Remove Item') ?></span></span></button>
									 
									<?php if ($product->isSaleable()): ?>
									    <button type="button" onclick="setLocation('<?php echo Mage::helper('wishlist')->getAddToCartUrl($item->getId()); ?>')" href="<?php echo Mage::helper('wishlist')->getAddToCartUrl($item->getId()); ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"  class="button btn-wishlist-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php endif; ?>
								</div>     
										
                        	</li>
						<?php if($i%$column == 0 || $i==$count) : ?>                        	
                        </ul>
                        <div class="clear clr"></div>
                        <?php endif; ?>
                        
                         
                        <?php endforeach; ?>
                        
                
                <?php else: ?>
                    <p class="wishlist-empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
                <?php endif ?> 
            
       
        
        <div class="buttons-set buttons-set2">
			<?php if($this->getWishlistItems()->count()): ?>
			<!-- 
				<button type="button" onclick="setLocation('<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>')" href="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update Wishlist')) ?>"  class="button btn-wishlist-update"><span><span><?php echo $this->__('Update Wishlist') ?></span></span></button>
				 -->
			    <button type="button" onclick="setLocation('<?php echo $this->getUrl('wishlist/index/share'); ?>')" name="save_and_share" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share Wishlist')) ?>" class="button btn-share"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
			<?php endif; //  array('wishlist_id'=>$this->getWishlistInstance()->getId()) ?>
		</div>   
		 </form>     
    </div>
    <?php echo $this->getChildHtml('bottom'); ?>    
<?php endif ?>
