<?php
/**
 * Shopping Cart Page
 */
?>
<?php
    $store_id = Mage::app()->getStore()->getStoreId();
?>
<?php $_code = 'affiliateplus' ?>
<form id="discount-affiliateplus-form" action="<?php echo $this->getUrl('affiliateplus/checkout/creditPost') ?>" method="post">
    <div class="discount">
        <div class="lable-title">
        <h2 class="legend"><?php echo $this->__('Affiliate Store Credit') ?></h2>
        </div>
        <div class="discount-form">
            <dl id="<?php echo $_code ?>_container">
                <dt class="<?php echo $_code ?>_credit">
                <input type="checkbox" name="<?php echo $_code ?>_credit" id="<?php echo $_code ?>_credit"<?php if ($this->getUseAffiliateCredit()): ?> checked="checked"<?php endif ?> value="1" onclick="showAffiliateCreditInput(this)" />
                <label for="<?php echo $_code ?>_credit" style="font-weight: bold; color: #666;"><?php echo $this->__('Check out with affiliate account balance (%s)', $this->getFormatedBalance()) ?></label>
                </dt>
                <dd id="<?php echo $_code ?>_credit_input" class="<?php echo $_code ?>_credit"<?php if (!$this->getUseAffiliateCredit()): ?> style="margin-top: 5px;display: none;"<?php endif ?>>
                    <div>
                        <label>
                            <?php echo $this->__('Enter an amount in your balance to spend on this order') ?>
                        </label>
                        <div class="input-box">
                            <input style="width: 100%;" class="input-text" type="text" value="<?php echo $this->getAffiliateCredit() ?>" title="<?php echo $this->__('Affiliate Store Credit') ?>" name="credit_amount" />
                        </div>
                    </div>
                    <br />
                    <div>
                        <div class="buttons-set">
                             <button type="submit" class="button button-config">
                                <span>
                                    <span><?php echo $this->__('Apply') ?></span>
                                </span>
                            </button>                                                            
                        </div>
                        <p></p>
                    </div>
                </dd>
                <dt></dt>                
            </dl>
        </div>

    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    function showAffiliateCreditInput(el) {
        if (el.checked) {
            $('<?php echo $_code ?>_credit_input').show();
        } else {
            $('<?php echo $_code ?>_credit_input').hide();
        }
    }
    var affiliateplusForm = new VarienForm('discount-affiliateplus-form');
//]]>
</script>
<style>
    #discount-affiliateplus-form h2.legend{
        background-color: #<?php echo Mage::getStoreConfig('affiliateplus/style_config/background_subtitle', $store_id) ?>;
        color:#<?php echo Mage::getStoreConfig('affiliateplus/style_config/sub_title_color', $store_id) ?>;
    }
    /*#discount-affiliateplus-form .btn-warning{
        background-color: #<?php echo Mage::getStoreConfig('affiliateplus/style_config/button_color', $store_id) ?>;
    }*/
</style>