<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Coming_Soon
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="plcs-block-mode live-mode" data-mode="live">
	<div class="plcs-status-enabled">Enabled</div>
	<div class="plcs-status-save">Save To Enable</div>
	<div class="plcs-icon-block">
		<div class="plcs-icon"></div>
		<div class="plcs-mode-name">Live Site</div>
		<div class="plcs-descr">Open your website to the world. Get ready for the big crowds!<br /><span class="plcs-b-link">Click to enable</span></div>
	</div>
	<button class="plcs-preview plcs-preview-live plcs-button-live">Preview</button>
</div>

<div class="plcs-block-mode cs-mode" data-mode="comingsoon">
	<div class="plcs-status-enabled">Enabled</div>
	<div class="plcs-status-save">Save To Enable</div>
	<div class="plcs-icon-block">
		<div class="plcs-icon"></div>
		<div class="plcs-mode-name">Coming Soon</div>
		<div class="plcs-descr">Great to start collecting emails from visitors or registering new members before the site is fully open.<br /><span class="plcs-b-link">Click to enable</span></div>
	</div>
	<button class="plcs-preview plcs-preview-comingsoon plcs-button-cs">Preview</button>
</div>

<div class="plcs-block-mode um-mode" data-mode="maintenance">
	<div class="plcs-status-enabled">Enabled</div>
	<div class="plcs-status-save">Save To Enable</div>
	<div class="plcs-icon-block">
		<div class="plcs-icon"></div>
		<div class="plcs-mode-name">Under Maintenance</div>
		<div class="plcs-descr">Set your live site in maintenance mode when applying some technical or design changes to your store.<br /><span class="plcs-b-link">Click to enable</span></div>
	</div>
	<button class="plcs-preview plcs-preview-maintenance plcs-button-um">Preview</button>
</div>