<li class="plcs-fields">
	<div class="plcs-field">
		<label for="confirmation" class="plcs-required"><em>*</em><?php echo $this->getLabel();?></label>
		<div class="plcs-input-box">
			<input type="password" name="confirmation" title="<?php echo $this->getLabel();?>" id="plcs-confirmation" placeholder="<?php echo $this->getPlaceholder();?>" class="input-text required-entry validate-cpassword" />
		</div>
	</div>
</li>