<li class="plcs-fields">
	<label for="plcs-conf_email_address" class="plcs-required"><em>*</em><?php echo $this->getLabel();?></label>
	<div class="plcs-input-box">
		<input type="text" name="confirm_email" id="plcs-conf_email_address" value="" placeholder="<?php echo $this->getPlaceholder();?>" title="<?php echo $this->getLabel();?>" class="input-text validate-email required-entry" />
	</div>
</li>