<li class="plcs-fields">
	<label for="plcs-city" class="plcs-required"><em>*</em><?php echo $this->getLabel();?></label>
	<div class="plcs-input-box">
		<input type="text" name="city" value="" placeholder="<?php echo $this->getPlaceholder();?>" title="<?php echo $this->getLabel();?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="plcs-city" />
	</div>
</li>