<li class="plcs-fields">
	<label for="plcs-company"><?php echo $this->getLabel();?></label>
	<div class="plcs-input-box">
		<input type="text" name="company" id="plcs-company" placeholder="<?php echo $this->getPlaceholder();?>" title="<?php echo $this->getLabel();?>" value="" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
	</div>
</li>