<li class="plcs-fields">
	<label for="plcs-zip" class="plcs-required"><em>*</em><?php echo $this->getLabel();?></label>
	<div class="plcs-input-box">
		<input type="text" name="postcode" value="" placeholder="<?php echo $this->getPlaceholder();?>" title="<?php echo $this->getLabel();?>" id="plcs-zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
	</div>
</li>