<li class="plcs-fields">
    <label for="plcs-region_id" class="plcs-required"><em>*</em><?php echo $this->getLabel();?></label>
    <div class="plcs-input-box">
        <select id="plcs-region_id" name="region_id" title="<?php echo $this->getLabel();?>" class="validate-select" style="display:none;">
           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
        </select>
        <script type="text/javascript">
        //<![CDATA[
            $('plcs-region_id').setAttribute('defaultValue',  "");
        //]]>
        </script>
        <input type="text" id="plcs-region" name="region" value="" placeholder="<?php echo $this->getPlaceholder();?>" title="<?php echo $this->getLabel();?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
    </div>
</li>