<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
<li class="plcs-fields">
    <label for="plcs-street_1" class="plcs-required"><em>*</em><?php echo $this->getLabel();?></label>
    <div class="plcs-input-box">
        <input type="text" name="street[]" value="" placeholder="<?php echo $this->getPlaceholder();?>" title="<?php echo $this->getLabel();?>" id="plcs-street_1" class="input-text <?php echo $_streetValidationClass ?>" />
    </div>
</li>