<?php
/**
 * Copyright (c) 2009-2014 Vaimo AB
 *
 * Vaimo reserves all rights in the Program as delivered. The Program
 * or any portion thereof may not be reproduced in any form whatsoever without
 * the written consent of Vaimo, except as provided by licence. A licence
 * under Vaimo's rights in the Program may be available directly from
 * Vaimo.
 *
 * Disclaimer:
 * THIS NOTICE MAY NOT BE REMOVED FROM THE PROGRAM BY ANY USER THEREOF.
 * THE PROGRAM IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE PROGRAM OR THE USE OR OTHER DEALINGS
 * IN THE PROGRAM.
 *
 * @category    Vaimo
 * @package     Vaimo_Klarna
 * @copyright   Copyright (c) 2009-2014 Vaimo AB
 */

?>

<br/>

<?php if ($this->getMessages()): ?>
    <table>
        <?php foreach ($this->getMessages() as $msg): ?>
            <tr>
                <td><?php echo $msg->getType(); ?></td>
                <td><?php echo $msg->getCode(); ?></td>
            </tr>
        <?php endforeach; ?>

    </table>

    <br/>
<?php endif; ?>

<table>
    <thead>
        <tr>
            <th><?php echo Mage::helper('klarna')->__('Country'); ?></th>
            <th><?php echo Mage::helper('klarna')->__('Description'); ?></th>
            <th><?php echo Mage::helper('klarna')->__('Months'); ?></th>
            <th><?php echo Mage::helper('klarna')->__('Invoice fee'); ?></th>
            <th><?php echo Mage::helper('klarna')->__('Start fee'); ?></th>
            <th><?php echo Mage::helper('klarna')->__('Minimum amount'); ?></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->getPClasses() as $pclass): ?>
        <tr>
        <?php if (isset($pclass['error'])): ?>
            <td><?php echo $pclass['error']; ?></td>
        <?php else: ?>
            <td><?php echo $pclass['countryname']; ?></td>
            <td><?php echo $pclass['description']; ?></td>
            <td><?php echo $pclass['months']; ?></td>
            <td><?php echo $pclass['invoicefee']; ?></td>
            <td><?php echo $pclass['startfee']; ?></td>
            <td><?php echo $pclass['minamount']; ?></td>
        <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

