<?php
/*
* Pts Prestashop Theme Framework for Prestashop 1.6.x
*
* @package   ptspagebuilder
* @version   5.0
* @author    http://www.prestabrain.com
* @copyright Copyright (C) October 2013 prestabrain.com <@emai:prestabrain@gmail.com>
*               <info@prestabrain.com>.All rights reserved.
* @license   GNU General Public License version 2
*/
if (isset($html)&& !empty($html)): ?>
<div class="alert <?php echo $alert_type; ?> <?php echo $addition_cls; ?>">
	<?php echo $html; ?>
</div>
<?php endif; ?>