<?php
if ($href): ?>
	<div class="widget-button block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
		<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
		<div class="block-title">
			<?php echo $widget_heading; ?>
		</div>
		<?php endif; ?>
		<div class="widget-inner block-content">
			<a href="<?php echo $href; ?>" class="btn <?php echo $color_button.$el_class." ".$size;?>" title="<?php echo $button_title;?>">
				<i class="<?php echo $icon; ?>"></i>
				<?php echo $button_title; ?>
			</a>
		</div>
	</div>
<?php endif;?>