<?php 
$id = "widget-raw-html".rand().time();
$enable_collapse = $this->getConfig("enable_collapse", 0);
if (isset($raw_html) && $raw_html): 
?>
<div class="widget-raw-html block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
	<div class="block-title">
		<?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#<?php echo $id; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
		<?php echo $widget_heading; ?>
	</div>
	<?php endif; ?>
	<div id="<?php echo $id; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">
		<?php echo $raw_html; ?>
	</div>
</div>
<?php endif; ?>