<?php
$id = rand().time();
if (isset($tabs)): ?>
<div class="widget-tab block <?php echo $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
	<div class="block-title">
		<?php echo $widget_heading; ?>
	</div>
	<?php endif; ?>
	<div class="widget-inner block-content">	
		<div id="widget-tabs<?php echo $id;?>" class="panel-group">
		
			<ul class="nav nav-tabs" id="widget-tab<?php echo $id;?>">
			  <?php foreach ($tabs as $key => $ac): ?>
			  <li class=""><a href="#tab<?php echo $id.$key;?>" ><?php echo $ac['header'];?></a></li>
			  <?php endforeach; ?>
			</ul>

			<div class="tab-content">
			 	<?php foreach ($tabs as $key => $ac): ?>
				  <div class="tab-pane" id="tab<?php echo $id.$key;?>" style="visibility:visible"><?php echo $ac['content'];?></div>
			 	<?php endforeach; ?>
	 		</div>

	</div></div>
</div>

<script type="text/javascript">
jQuery('#widget-tabs<?php echo $id; ?> a').click(function (e) {
	e.preventDefault();
	jQuery(this).tab('show');
})
jQuery('#widget-tabs<?php echo $id; ?> a:first').tab('show'); 
</script>

<?php endif; ?>