<?php
/**
* This file is released under a custom license by Avenla Oy.
* All rights reserved
*
* License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/
* For questions and support - klarna-support@avenla.com
*
* @category   Avenla
* @package    Avenla_KlarnaCheckout
* @copyright  Copyright (c) Avenla Oy
* @link       http://www.avenla.fi
*/

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>

<div class="comment">
	<div style="padding:10px;background-color:#fff;border:1px solid #ddd;margin-bottom:7px;">
		<img src="<?php echo $logoSrc; ?>" alt="Klarna Checkout" />
		<a href="<?php echo $apiLink; ?>" target="_blank" style="float:right;"><?php echo $this->__('Klarna API Documentation'); ?></a>
		<a href="<?php echo $documentationUrl; ?>" target="_blank" style="float: right;clear: both;margin-top: 10px;">
			<?php echo $this->__('Avenla Klarna Checkout module documentation'); ?>
		</a>

		<div class="infoContent">
			<?php
				$alerts = $this->getAlerts();
				if(!empty($alerts)):
			?>
				<ul>
					<?php foreach($alerts as $alert): ?>
						<li class="klarna_alert" style="color:red;">
						<?php echo '<b>' . $this->__('Warning!') .'</b> '. $this->__($alert); ?></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>

			<b>
				<a href="<?php echo Avenla_KlarnaCheckout_Model_Config::LICENSE_URL ?>" target="_blank">
					<?php echo $this->__("License agreement"); ?>
				</a>
			</b>

		</div>
	</div>
</div>