
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            
            <input type="hidden" name="return_url" value="<?php echo $this->getUrl('wishlist'); ?>" />
        </div>

        
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>


            
            <?php echo $this->getChildHtml('product_type_data') ?>
            

           

            

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
            
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
	            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
	        <?php endif;?>

        

        <div class="clearer"></div>
        
    </form>
    <script type="text/javascript">
    //<![CDATA[
    	jQuery('add')
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
        <?php
		$helperConfig	= Mage::helper('guestwishlist/config'); 
		?>
        jQuery(document).ready(function(){

    		var options = {
    			'elements':        {
    				'add'		: '.link-wishlist',
    				'remove'	: '#wishlist-sidebar .btn-remove, .btn-wishlist-remove',
    				'cart'		: '.btn-wishlist-cart',
    				'update'	: '.btn-wishlist-update'
    			},
    			'translate'		: {
    				'add'		: '<?php echo $this->__('Add to Wishlist'); ?>',
    				'remove'	: '<?php echo $this->__('Remove from Wishlist'); ?>',
    				'error'		: '<?php echo $this->__("Sorry, We can\'t process your request. Please try again in next time.");  ?>',
    				'confirm'	: '<?php echo $this->__('Are you sure you would like to remove this item from the wishlist?'); ?>',
    				'login'		: '<?php echo $this->__('Please login before add to wishlist.'); ?>'
    			},
    			'area'			: {
    				'cart'			: jQuery('.checkout-cart-index .cart'),
    				'wishlist'		: jQuery('.wishlist-index-index .my-wishlist'),
    				'sidebar'		: jQuery('.block-wishlist'),
    			},
    			'count'			: {
    				'wishlist'		: jQuery('[href$="wishlist/"]', jQuery('.header .links')),
    				'cart'			: jQuery('.top-link-cart', jQuery('.header .links'))
    			},			
    			'url'			: {
    				'add'			: '<?php echo $this->getUrl('wishlist/index/add', array('product'=>'{product_id}', 'form_key' => Mage::getSingleton('core/session')->getFormKey())); ?>',
    				'remove'		: '<?php echo $this->getUrl('wishlist/index/remove', array('item'=>'{item_id}')); ?>',
    			},
    			'added'			: <?php echo Mage::helper('core')->jsonEncode(Mage::helper('guestwishlist')->parseWishlistAdded()); ?>,		
    			'selector_add'	: 'a[href*="wishlist/index/add/product/{product_id}/"]',
    			'class_has_item': 'added',
    			'number_col'	: 3,
    			'showMsg'		: <?php echo $helperConfig->canShowMsg(); ?>,
    			'enable'		: <?php echo $helperConfig->isEnable() ? 1 : (Mage::getSingleton('customer/session')->isLoggedIn() ? 1 : 0) ; ?>,
    			'useAjax'		: <?php echo $helperConfig->useAjax(); ?>,
    		};		
    		
    		jQuery(this).GuestWishlist(options);
    	});
    	
    //]]>
    </script>
    </div>

    
</div>
