<?php
/**
 * Affiliate's navigation template
 */
?>
<!--<div style="margin-top:5px;">
	<a rel="nofollow" target="_blank" href="http://www.magestore.com/affiliateplus/">
		<img src="<?php echo Mage::getBaseUrl('skin') ?>frontend/default/default/css/magestore/trademark.png">
	</a>
</div>	-->
<br/>
<div class="affiliateplus-account-bottom">
	<?php if(Mage::helper('affiliateplus/account')->customerNotLogin()): ?>
		<div class="col-button col-lg-4 col-md-4 col-sm-4 col-xs-12">
		<button onclick="location.href='<?php echo $this->getUrl('affiliateplus/account/login') ?>'" class="form-button btn-login">
                    <span><?php echo $this->__('Login'); ?></span>
		</button>
		</div>
	<?php endif ?>
	<?php if(Mage::helper('affiliateplus/account')->accountNotRegistered()): ?>
	<div class="col-button col-lg-4 col-md-4 col-sm-4 col-xs-12">
		<button onclick="location.href='<?php echo $this->getUrl('affiliateplus/account/register') ?>'" class="form-button btn-signup">
                    <span><?php echo $this->__('Signup'); ?></span>
		</button>
		</div>
	<?php endif ?>
	<div class="col-button col-lg-4 col-md-4 col-sm-4 col-xs-12">
	<button onclick="location.href='<?php echo $this->getUrl('contacts') ?>'" class="form-button btn-contact">
            <span><?php echo $this->__('Contact Us'); ?></span>
            
	</button>
            </div>
</div>