<?php
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 * 
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/ 
 * For questions and support - klarna-support@avenla.com
 * 
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi 
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>

<?php if ($this->isPossibleOnepageCheckout()):?>
	<a href="<?php echo $this->getCheckoutUrl() ?>"
		<?php if ($this->isDisabled()): ?> class="disabled"<?php endif; ?>>
		<?php echo $this->__('Proceed to Checkout') ?>
	</a>
<?php endif?>
