<?php
/**
 * Payments history template
 */
?>
<?php
$store_id = Mage::app()->getStore()->getStoreId();
$check_responsvie = Mage::getStoreConfig('affiliateplus/style_config/responsive_enable', $store_id);
 if($check_responsvie)
     $class_name = 'col-lg-9 col-md-9 col-sm-12 col-xs-12';
 else
     $class_name = 'col-lg-9 col-md-9 col-sm-9 col-xs-9';
?>

<div class="aff-main-content <?php echo $class_name; ?>">
<div class="aff-title">
	<h2>
    <?php if (Mage::helper('affiliateplus/account')->disableWithdrawal()): ?>
        <?php echo $this->__('Store Credits History') ?>
    <?php else: ?>
        <?php echo $this->__('Withdrawal History') ?>
    <?php endif ?>
    </h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('payment_miniform') ?>

<div class="clear">&nbsp;</div>
<?php echo $this->getGridHtml() ?>
</div>