<?php 
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 * 
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/ 
 * For questions and support - klarna-support@avenla.com
 * 
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi 
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>
<div class="klarna-widget klarna-badge-tooltip"
    data-eid="<?php echo Mage::getModel('klarnaCheckout/config')->getKlarnaEid(); ?>"
    data-locale="<?php echo $this->getLocale(); ?>"
    data-badge-name="<?php echo $this->getData('methodslayout'); ?>-<?php echo $this->getData('color') ?>"
    data-badge-width="<?php echo $this->getWidth(); ?>"
    data-layout="<?php echo $this->getData('tooltiplayout'); ?>">
</div>