<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="product-view prod_<?php echo $_product->getTypeId() ?>">
    <div class="product-essential row">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="col-sm-5 col-md-5">
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>

            </div>
            </div>
            <div class="col-sm-7 col-md-7">
            <div class="view-product-shop status_stock_<?php echo $_product->isSaleable() ?>">
                <div class="clearfix"></div>

                <?php echo $this->getChildHtml('product_type_data') ?>

                <div class="row">
                    <div class="col-xs-12 col-sm-12">
                    <?php  $pro=Mage::getModel('catalog/product')->load($_product->getId());?>
                        <div class="pro-price">
                            <div class="pro-price-info">
                                <?php echo $this->getPriceHtml($_product); ?>
                                <?php echo $this->getChildHtml('bundle_prices') ?>
                                <?php echo $this->getTierPriceHtml() ?>
                            </div>
                        </div>

                        <div class="Klarna" id="helpKlarna" data-toggle="modal" data-target="helpKlarnaModal">
                        <h3><?php echo $this->__('Klarna');?></h3><span>?</span><p><?php echo $this->__('Delbetala med klarna');?></p>
                        </div>

                        <!-- Modal -->
                        <div id="helpKlarnaModal" class="modal" role="dialog">
                          <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title"><?php echo $this->__('Klarna');?></h4>
                              </div>
                              <div class="modal-body">
                                <p>
                                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('klarna_info')->toHtml(); ?>
                                </p>
                              </div>
                            </div>

                          </div>
                        </div>

                    </div>


                    <div class="col-xs-12 col-sm-12">
                        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                            <style>
                                .col-sm-12 .product-options
                                {
                                    float: left;
                                    margin: 0;
                                    width: 40%;
                                }
                                .col-sm-12 .add-to-box
                                {
                                    float: left;
                                    margin: 91px 0 0;
                                    width: 50%;
                                }
                                .col-sm-12 .wishlistbg
                                {
                                    float: left;
                                    width: 15%;
                                    margin: 120px 0 0 0;
                                }
                            </style>
                        <?php endif;?>

                        <div class="add-to-box">
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?> 
                        </div>

                    </div>
            
                <?php echo $this->getChildHtml('alert_urls') ?>
               

                <?php $stockItem = $_product->getStockItem(); ?>
                <?php if (!$stockItem->getIsInStock()): ?>
                <div class="col-sm-12">
                    <span class="out-of-stock-prod"><span class="main_icon">!</span><span class="right_part_icon_text"><h2><?php echo $this->__('Slut i lager');?></h2><a href="javascript:void(0)"><?php echo $this->__('Skapa en bevakning pa varan.');?></a></span></span>
                </div>
                <?php endif; ?>

                <div class="col-xs-12 col-sm-12">
                    <div class="pro-details-description pro-desct">
                        <?php echo $_product->getDescription();?>
                    </div> 
                </div>
                <?php echo $this->getChildHtml('other');?>
            </div>
            </div>
            <?php echo $this->getChildHtml('related_products') ?>

            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>
    <?php echo $this->getChildHtml('upsell_products') ?>

</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('store')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('catalog/product_list_related')->setTemplate('catalog/product/list/related.phtml')->toHtml(); ?>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.opt-lv1').click(function(){
            jQuery('.box-topt').toggle();
            if(jQuery('.box-topt').css('display') != 'none') {
                jQuery('.opt-icon').css('margin-top', '-35px');
            } else {
                jQuery('.opt-icon').css('margin-top', '15px');
            }
        });

        jQuery('#helpKlarna').click(function(event){
            jQuery('#helpKlarnaModal').toggle();
        });
        
        jQuery('#helpKlarnaModal .close').click(function(event){
            jQuery('#helpKlarnaModal').hide();
        });

         
        jQuery('#helpKlarnaModal').click(function(evt){    
           if(evt.target.class == "modal-dialog")
              return;
           if(jQuery(evt.target).closest('.modal-dialog').length)
              return;             
           jQuery('#helpKlarnaModal').hide(); 

        });  

        jQuery('.view-product-shop .btn-cart').click(function() {
            if (jQuery('.super-attribute-select').hasClass('validation-failed')) {
                jQuery('.view-product-shop .add-to-box').addClass('fail-vali');
            } else {
                jQuery('.view-product-shop .add-to-box').removeClass('fail-vali');
            }
        });

        
    });
</script>
