<?php
/**
 * Sales transaction history template
 */
?>
<?php
$store_id = Mage::app()->getStore()->getStoreId();
$check_responsvie = Mage::getStoreConfig('affiliateplus/style_config/responsive_enable', $store_id);
 if($check_responsvie)
     $class_name = 'col-lg-9 col-md-9 col-sm-12 col-xs-12';
 else
     $class_name = 'col-lg-9 col-md-9 col-sm-9 col-xs-9';
?>
<div class="aff-main-content <?php echo $class_name; ?>">
<div class="aff-title">
	<h2><?php echo $this->__('Commissions') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('payment_miniform') ?>

<?php echo $this->getChildHtml('sales_statistic') ?>

<?php if ($commissionTabs = $this->getCommissionTabs()): ?>
<ul class="nav nav-tabs">
	<?php foreach ($commissionTabs as $name => $tab): ?>
		<?php if ($name == $this->getActiveTab()): ?>
		<li class="active">
                    <a><span><?php echo $tab['label'] ?></span></a>
		</li>
		<?php else: ?>
		<li>
			<a href="<?php echo $tab['link'] ?>" title="<?php echo $tab['label'] ?>">
				<span><?php echo $tab['label'] ?></span>
			</a>
		</li>
		<?php endif ?>
	<?php endforeach ?>
</ul>
<?php endif ?>

<?php echo $this->getTransactionHtml() ?>
</div>