<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Coming_Soon
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

$preview = Mage::getSingleton('core/session')->getData(Plumrocket_ComingSoon_Helper_Data::PREVIEW_PARAM_NAME);
?>

<?php if(!empty($preview['live'])): ?>
    <div class="global-site-notice demo-notice">
        <div class="notice-inner"><p><?php echo $this->__('This is a preview of "Live Mode". To disable the preview and browse the website as a guest, please click "<a href="%s">Stop Preview</a>"', $this->getUrl('comingsoon/index/preview', array('mode' => 'live', 'action' => 'stop'))); ?></p></div>
    </div>
<?php endif; ?>
