<?php
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 *
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/
 * For questions and support - klarna-support@avenla.com
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>

<div id="klarnaMsg" style="display:none"><h2></h2></div>

<div id="klarnaWrapper" name="klarnaWrapper">
    <div id="klarnaOverlay"></div>
    <div id="klarnaFrame"></div>
</div>

<script>
    function loadFrame()
    {
        var kcoloadurl = '<?php echo $this->getLoadUrl(); ?>';

        new Ajax.Request(kcoloadurl, {
            method:'POST',
            onSuccess: function(k) {
                var response = eval("(" + k.responseText + ")");
                if(response.msg){
                    $('klarnaMsg').update('<h2>'+ response.msg +'</h2>').show();
                    if(!response.kcologin){
                        $('klarnaOverlay').show();
                    }
                    else{
                        $('klarnaOverlay').hide();
                    }
                }
                else{
                    $('klarnaMsg').update('').hide();
                    $('klarnaOverlay').hide();

                    if(response.validationMsg){
                        $('klarnaMsg').update('<h2 class="kco-validation-message">'+ response.validationMsg +'</h2>').show();
                    }
                }

                if(response.klarnaframe){
                    $('klarnaFrame').update(response.klarnaframe);
                    waitForKlarna();
                }
            }
        });
    }

    function waitForKlarna(){
        if(typeof window._klarnaCheckout !== "undefined"){
            window._klarnaCheckout(function(api) {
                api.on({
                    'change': function(data){
                    	console.log(data);
                    	if(typeof data.email !== "undefined"){
                    		addEmailToQuote(data.email);
                		}
                    }
                });
            });
        }
        else{
            setTimeout(function(){
                waitForKlarna();
            },250);
        }
    }

    function addEmailToQuote(email)
    {
    	var needForCheck = <?php echo $this->checkQuoteEmail() ? 'true' : 'false'; ?>;

    	if(!needForCheck)
    		return false;

    	var kcoemailurl = '<?php echo $this->getAddEmailUrl(); ?>';
		new Ajax.Request(kcoemailurl, {
            method:'POST',
            parameters: {klarna_email:email}
        });
    }


    document.observe('dom:loaded', function(){
        loadFrame();
    });

    _send = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.send = function() {
        var callback = this.onreadystatechange;
        this.onreadystatechange = function() {
            if (this.readyState == 4) {
                var response = eval("(" + this.response + ")");
				if(response !== undefined){
				    if (response.klarnaframe === undefined && response.msg === undefined)
						loadFrame();
				}
            }
            callback.apply(this, arguments);
        }
        _send.apply(this, arguments);
    }
</script>