<?php
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 *
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/
 * For questions and support - klarna-support@avenla.com
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>
<?php $helper = Mage::helper("klarnaCheckout"); ?>
<a href="<?php echo $helper->getCartUri();?>" class="klarnaLink">
	<img src="<?php echo $helper->getLogoSrc(); ?>" alt="Klarna Checkout" />
	<p class="klarnaLinkText"><?php echo $helper->__(Mage::getModel('klarnaCheckout/config')->getLinkText());?></p>
</a>

<?php echo $this->getChildHtml('original'); ?>
