<?php 
/**
 * This file is released under a custom license by Avenla Oy.
 * All rights reserved
 * 
 * License and more information can be found at http://productdownloads.avenla.com/magento-modules/klarna-checkout/ 
 * For questions and support - klarna-support@avenla.com
 * 
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 * @copyright  Copyright (c) Avenla Oy
 * @link       http://www.avenla.fi 
 */

/**
 * Avenla KlarnaCheckout
 *
 * @category   Avenla
 * @package    Avenla_KlarnaCheckout
 */
?>
<form id="kcoNewsLetterForm">
    <input type="checkbox" id="signNewsletter" name="signNewsletter" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" 
    	<?php echo $this->isChecked() ? 'checked="checked"' : ''; ?>
	/>
    <label for="signNewsletter">
        <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>
    </label>


</form>
<p id="kcoNewsMessage" style="display:none;"></p>

<script>
	$$('#kcoNewsLetterForm input[type="checkbox"]').invoke('observe','click',function(field) {
		var newsletterurl = '<?php echo $this->getUrl("klarnaCheckout/KCO/newsletter/", array("_secure" => true)) ?>';
        var box = this;
		if(box.checked)
			newsletterurl += 'status/1';

	    new Ajax.Request(newsletterurl, {
	    	method:'POST',
	    	onSuccess: function(k) {
                var response = eval("(" + k.responseText + ")");
                if(response.letter_msg){
                    $('kcoNewsMessage').update(response.letter_msg).show();
                    box.checked = false;
                }
                else{
                    $('kcoNewsMessage').update('').hide();
                }
            }
	    });
	});
</script>